# Generated by Django 4.2.2 on 2023-07-02 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_date_event_finish_date_event_start_date'),
        ('app', '0005_spend'),
    ]

    operations = [
    ]
