# Generated by Django 4.2.2 on 2023-07-02 03:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_merge_20230702_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spend',
            name='author',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='user_for_spend', to=settings.AUTH_USER_MODEL),
        ),
    ]
