# Generated by Django 4.2.2 on 2023-07-02 03:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0007_alter_spend_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spend',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_for_spend', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='spend',
            name='spend',
            field=models.IntegerField(default=0),
        ),
    ]
