# Generated by Django 4.2.2 on 2023-07-03 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_spend_spend'),
    ]

    operations = [
        migrations.AddField(
            model_name='spend',
            name='date',
            field=models.IntegerField(default=1),
        ),
    ]
