# Generated by Django 4.2.2 on 2023-07-03 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_event_category'),
        ('app', '0010_spend_date'),
    ]

    operations = [
    ]
