# Generated by Django 4.2.2 on 2023-07-10 06:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_event_finish_date_alter_event_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='finish_date',
            field=models.DateField(default=datetime.date(2023, 7, 10)),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateField(default=datetime.date(2023, 7, 10)),
        ),
    ]
