# Generated by Django 4.2.2 on 2023-07-10 06:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_event_finish_date_alter_event_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='finish_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 10, 15, 48, 38, 818616)),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 10, 15, 48, 38, 818616)),
        ),
    ]
